"""
Renders a generated prospectus (markdown) into a downloadable, letterhead-styled PDF.

Uses `markdown` + `xhtml2pdf` (pure Python, no system-level dependencies like
wkhtmltopdf or Cairo/Pango required) so this works the same in a Docker
container as it does on a laptop.
"""
import datetime as dt
from io import BytesIO

import markdown as md
from xhtml2pdf import pisa

PDF_STYLE = """
<style>
    @page {
        size: A4;
        margin: 2.4cm 2cm 2cm 2cm;
    }
    body {
        font-family: Helvetica, Arial, sans-serif;
        color: #1B2A4A;
        font-size: 11pt;
        line-height: 1.5;
    }
    .letterhead {
        border-bottom: 2px solid #B08D57;
        padding-bottom: 10px;
        margin-bottom: 22px;
    }
    .letterhead .eyebrow {
        font-size: 8.5pt;
        letter-spacing: 2px;
        text-transform: uppercase;
        color: #B08D57;
        font-weight: bold;
    }
    .letterhead .meta {
        font-size: 8.5pt;
        color: #6B6E76;
        margin-top: 2px;
    }
    h1 {
        font-size: 22pt;
        color: #1B2A4A;
        margin-bottom: 4px;
    }
    h2 {
        font-size: 13pt;
        color: #1B2A4A;
        border-bottom: 0.75px solid #D8D2C4;
        padding-bottom: 4px;
        margin-top: 20px;
        margin-bottom: 8px;
    }
    p, li {
        font-size: 10.5pt;
    }
    a {
        color: #1B2A4A;
    }
    .footer-note {
        margin-top: 26px;
        padding-top: 8px;
        border-top: 0.75px solid #D8D2C4;
        font-size: 8pt;
        color: #6B6E76;
    }
</style>
"""


def markdown_to_pdf(company_name: str, markdown_text: str) -> bytes:
    if not markdown_text.strip():
        raise ValueError("Nothing to export — the prospectus is empty.")

    body_html = md.markdown(markdown_text, extensions=["extra", "sane_lists"])
    generated_on = dt.datetime.now().strftime("%B %d, %Y")

    full_html = f"""
    <html>
    <head>{PDF_STYLE}</head>
    <body>
        <div class="letterhead">
            <div class="eyebrow">Prospectus &middot; Confidential Draft</div>
            <div class="meta">Prepared for {company_name} &middot; Generated {generated_on}</div>
        </div>
        {body_html}
        <div class="footer-note">
            Generated by Prospectus — an AI research &amp; document assistant.
            Verify all facts before external distribution.
        </div>
    </body>
    </html>
    """

    output = BytesIO()
    result = pisa.CreatePDF(src=full_html, dest=output)
    if result.err:
        raise ValueError("Failed to render PDF from the generated prospectus.")

    return output.getvalue()